language: objective-c
osx_image: xcode8
script:
- cd URITemplate && swift package generate-xcodeproj
- xcodebuild -project Mockingjay.xcodeproj -scheme Mockingjay test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick
